name: Message
version: '${project.version}'
main: net.mckitsu.message.Message
api-version: '1.20'

commands:
  msgreload:
    description: To do config reload.

    usage: /<command>

  channel:
    description: To do join and leave.

    usage: /<command>